%GENERAL Summary of this function goes here
%   Detailed explanation goes here
pos = [10 5 480 380];
h.panel(1) = uipanel('Units','pixel','Title','General','FontSize',10,...
    'Position',pos + [0 235 0 -240], 'BackgroundColor', [224   223   227]/255 );

load icon.mat
global cfg
%% File directory for your sample
uicontrol('Parent',h.panel(1),'Units','pixel',...
    'Style','text',...
    'Position',[10 100 150 20],...
    'String', 'File directory for your sample:',...
    'HorizontalAlignment','Left');

h.edit(1)=uicontrol('Parent',h.panel(1),'Units','pixel',...
    'Style','Edit',...
    'BackgroundColor','w',...
    'Position',[170 105 190 20],...
    'ToolTipString','File directory for your sample',...
    'String', cfg.sampledir,...
    'Callback', 'cfg.sampledir=get(gcbo,''String'');');

uicontrol('Parent',h.panel(1),'Units','pixel',...
    'Style','Pushbutton',...
    'Position',[370 105 25 20],...
    'cdata', icon.folder,...
    'ToolTipString','Browse',...
    'Userdata',h.edit(1),...
    'Callback','[filename, pathname] = uigetfile(''*.dpt'', ''File for your sample'');cfg.sampledir=fullfile(pathname,filename);set(get(gcbo,''Userdata''), ''String'',cfg.sampledir);clear filename pathname;');

%% Sample ID
uicontrol('Parent',h.panel(1),'Units','pixel',...
    'Style','text',...
    'Position',[10 60 150 20],...
    'String', 'Sample ID:',...
    'HorizontalAlignment','Left');

h.edit(2)=uicontrol('Parent',h.panel(1),'Units','pixel',...
    'Style','Edit',...
    'BackgroundColor','w',...
    'Position',[170 65 190 20],...
    'ToolTipString','Sample ID',...
    'String', cfg.sampleID,...
    'Callback', 'cfg.sampleID = get(gcbo,''String'');');

%% Outpath
uicontrol('Parent',h.panel(1),'Units','pixel',...
    'Style','text',...
    'Position',[10 20 150 20],...
    'String', 'Figure output directory:',...
    'HorizontalAlignment','Left');

h.edit(3)=uicontrol('Parent',h.panel(1),'Units','pixel',...
    'Style','Edit',...
    'BackgroundColor','w',...
    'Position',[170 25 190 20],...
    'ToolTipString','Figure output directory',...
    'String', cfg.outpath,...
    'Callback', 'cfg.outpath=get(gcbo,''String'');');

uicontrol('Parent',h.panel(1),'Units','pixel',...
    'Style','Pushbutton',...
    'Position',[370 25 25 20],...
    'cdata', icon.folder,...
    'ToolTipString','Browse',...
    'Userdata',h.edit(3),...
    'Callback','tmp=uigetdir(cfg.outpath);cfg.outpath=tmp;set(get(gcbo,''Userdata''), ''String'',cfg.outpath);clear tmp;');
